### ISSUE TITLE
Dropping value tests fail by chance

### ISSUE THREAD

**Issue by jerry73204** [Gregory-Meyer/cht#15]
The `drop_value` and `drop_many_values_concurrent` are more probable to fail with `cargo test --release`. Here is the [screenshot](https://imgur.com/ywnGaIR) of the occurrence.

**Comment by Gregory-Meyer** [comment]
I _think_ that this is because crossbeam-epoch doesn't provide a reliable API for running your deferred functions on command. In [94fafef](https://github.com/Gregory-Meyer/cht/commit/94fafefb5a30df4b4f438295e9be5adc93d07d03) I changed the implementation of `run_deferred` to allocate objects in addition to flushing the thread-local list of deferred functions. Hopefully, the behavior we're seeing here is just a result of crossbeam-epoch's API decisions.

Can you checkout version 0.4.0 and see if you can reproduce this behavior? I'll loop through the tests for a few hours on my end as well.

**Comment by jerry73204** [comment]
I looped the tests for several times and they passed in a row so far.

**Comment by Gregory-Meyer** [comment]
I've been running the tests on repeat as well, no errors so far. I'm going to say this one is fixed!
